---
# tasks file for roles/database
- name: Launch database
  docker_container:
    name: database
    image: poeen/tp-devops-epf:database
    env:
      POSTGRES_DB: "db"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"  
    networks: 
      - name: "network"
