---
# tasks file for roles/app
- name: launch App
  docker_container:
    name: backend
    image: poeen/tp-devops-epf:simple-api
    env:
      SPRING_DTASOURCE_PASSWORD: "pwd"
      SPRING_DTASOURCE_USERNAME: "usr"
      SPRING_DTASOURCE_URL: "jbc:postgresql://database:5432/db"
    networks:
      - name: network
